# Generated by Django 2.1.7 on 2019-03-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190304_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='completed_date',
            new_name='cdate',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='created_date',
        ),
    ]
